const String mySummary = 'Olá, meu nome é Gabriel Ribeiro e tenho 25 anos.'
    '\nNão costumo trabalhar com MobX, foi meu primeiro projeto utilizando ele. Está simples, apenas cumprindo o que foi pedido.\n'
    'Atualmente, tenho um trabalho part time em uma empresa que processa pagamentos. Eu mantenho com eles 2 apps: um app de gestão dos pagamentos realizados, pendentes, entradas de '
    'dinheiro do usuário, etc; o outro app é relativo a execução dos pagamentos em si e a criação de ordens de pagamento, este'
    ' último está em processo de validação para substituir o aplicativo legado antigo que  está descontinuado.'
    '\nCostumo utilizar bibliotecas como o Flutter Modular para a navegação, injeção de dependências e modularização do projeto.'
    '\nAlém disso, gosto de trabalhar com BLoC e Cubit na maior parte do tempo, porém, opto por ValueNotifier quando é um aplicativo'
    ' mais simples de gerenciar.'
    '\nNos aplicativos que já fiz tive experiência com:\n- Localização do usuário\n- Internacionalização '
    '(múltiplos idiomas)\n- Testes unitários\n- Criação e validação de formulários (incluindo validação de pagamentos e cartão de'
    ' crédito)\n- Autenticação com biometria\n- Animação básica\n- PWAs com Flutter\n- Aplicações para Windows com Flutter\n- '
    'Aplicações para Web com Flutter\n- Builds de múltiplos flavors (web, iOS e Android)\n- Publicação nas lojas Android e Apple\n- '
    'Firebase\n\n'
    'Gostaria de me aprofundar mais futuramente:\n- Design de UI/UX mais rebuscados\n- Processo de build para Apple\n-'
    ' Testes de Widgets/Telas\n- Testes de Integração\n- Testes automatizados';
